id: I42438E72
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T10:50:29+00:00'
last_modified: '2022-06-08T05:11:32.835773+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD415
  title: གསང་སྔགས་ངག་དོན་འཕྲུལ་གྱི་ལྡེ་མིག་སོགས། （མཚན་ཉིད་སྐོར།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    DA2D:
      image_group_id: I4PD4684
      title: ''
      total_pages: 448
      order: 1
      base_file: DA2D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
