id: P005598
initial_creation_type: ocr
source_metadata:
  id: bdr:W3PD415
  title: གསང་སྔགས་ངག་དོན་འཕྲུལ་གྱི་ལྡེ་མིག་སོགས། （མཚན་ཉིད་སྐོར།）
  author: ''
  volumes:
    de35b655afb14af5921716a029222472:
      image_group_id: I4PD4684
      title: ''
      volume_number: 1
      total_pages: 448
